services:
  web:
    build: .
    container_name: new_user_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
    networks:
      - django_network
networks:
  django_network:
    name: django_network
    external: true
