# Generated by Django 5.2 on 2025-04-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdoc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeName',
            new_name='Employee',
        ),
    ]
