# Generated by Django 5.2 on 2025-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdoc', '0003_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
