# Generated by Django 5.2 on 2025-04-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdoc', '0004_employee_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneextension',
            name='employee',
        ),
        migrations.DeleteModel(
            name='CellPhone',
        ),
        migrations.DeleteModel(
            name='PhoneExtension',
        ),
    ]
