# Generated by Django 5.2 on 2025-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdoc', '0005_remove_phoneextension_employee_delete_cellphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
