# Generated by Django 5.2 on 2025-04-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdoc', '0006_alter_employee_domain_delete_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
