# Generated by Django 5.2 on 2025-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdoc', '0007_alter_employee_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
