# Generated by Django 4.2.20 on 2025-04-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdoc', '0008_alter_employee_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
