# Generated by Django 4.2.20 on 2025-04-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdoc', '0009_employee_cell_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
