# Generated by Django 4.2.20 on 2025-04-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdoc', '0010_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eld_User',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
